### ISSUE TITLE
Icon for fast forwarding 

### ISSUE THREAD

**Issue by adamazmil** [venkaa28/music_visualizer#23]
For local music playback the icons you guys are using for skipping 10 seconds are the same ones for skipping to another song from the Spotify ones. It was a little confusing at first.

Severity: Medium 

Suggestion: Netflix uses the 10 second icon for fast forwarding purposes. That would be a good icon

**Comment by zachquasius** [comment]
Needs merging but fixed by adding icons and switching when input source is switched
