### ISSUE TITLE
Profile Page return Bugs out Music Visualizer (Local Play) --livedeploy

### ISSUE THREAD

**Issue by adamazmil** [venkaa28/music_visualizer#24]
Upon clicking profile page in visualizer page returning to the music visualizer page cause Local playing visualizer to be non responsive. 
Steps to reproduce
1.  Click Profile page icon 
2. Return to visualizer page clicking the logo

Severity: High 
Suggestions: Possibly due to not fully reloading the state of the app?

**Comment by zachquasius** [comment]
Was an issue with not closing audio instances when routing away from the page. Needs merging but fixed by handling page routing
