### ISSUE TITLE
Profile page return bugs out Music Visualizer (Spotify Play) --livedeploy

### ISSUE THREAD

**Issue by adamazmil** [venkaa28/music_visualizer#25]
Return To Music Visualizer from Profile Page creates a new instance of Music Visualizer in Spotify. The visualizer seems to be playing from the old instance which causes it to bug out from not being able to receive data?. Manually playing the new instance prompts the visualizer to work again.  
A behavior that could be causing this is that the music continues to play when going to the profile page.

Severity: High

Suggestion: Kill the music visualizer when transitioning to the profile page.

**Comment by zachquasius** [comment]
Similar issue to local files, also needs merging but fixed in the same way
