### ISSUE TITLE
Spotify account not always remembered

### ISSUE THREAD

**Issue by Sjwagner5** [venkaa28/music_visualizer#28]
If I log out and log back in immediately, my Spotify account is remembered. However, when I log out and log back in a while later, I have to log back into my Spotify account.

Severity: Low

Suggestion: I am not sure how you are storing this information, but maybe it is not being stored properly somewhere

**Comment by venkaa28** [comment]
Hey, The Spotify token is only valid for an hour. This is a requirement of Spotify's API to reauthenticate after an hour (when the token expires).
