### ISSUE TITLE
Switching from ocean scene to other scenes while playing Spotify

### ISSUE THREAD

**Issue by Sjwagner5** [venkaa28/music_visualizer#29]
If you are playing Spotify and watching the ocean scene, and switch to either the plane scene, the particle cloud scene, or the sphere scene, the image from the new scene is not centered on your screen. If you go from the ocean scene to the nebula screen, the image from the new scene does not appear at all.

Severity: High

Suggestion: I am assuming this has something to do with how you render other scenes after the ocean scene

**Comment by zachquasius** [comment]
Issue had to do with how async promises were being used. FIxed, just needs merging
