### ISSUE TITLE
Shark rendering issues

### ISSUE THREAD

**Issue by Sjwagner5** [venkaa28/music_visualizer#30]
If you are playing a song while watching the ocean scene, then switch to a new scene, and then switch back to the ocean scene, the shark does not re-appear with the ocean scene. The only way to get the shark to render again is to switch tabs and come back or let the current song finish and let the next song start.

Severity: Medium

Suggestion: I like the shark but if you can not get it to render consistently, I would leave it out completely. It would not take away much from the scene if it was lost.

**Comment by zachquasius** [comment]
Removed the shark
